name: D:\conda_envs\thesis_nlp
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.19=hbb43b14_0
  - packaging=25.0=py310haa95532_1
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.10.1=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.1
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cryptography==46.0.4
      - distro==1.9.0
      - fasttext-wheel==0.9.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - jiter==0.12.0
      - joblib==1.5.3
      - nltk==3.9.2
      - numpy==2.2.6
      - openai==2.16.0
      - pybind11==3.0.1
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygithub==2.8.1
      - pyjwt==2.11.0
      - pynacl==1.6.2
      - regex==2026.1.15
      - requests==2.32.5
      - sniffio==1.3.1
      - tqdm==4.67.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
prefix: D:\conda_envs\thesis_nlp
